#!/usr/bin/env node
// Generates docs/test-report.md from the Vitest suite.
//
//   npm run test:report
//
// Runs Vitest's JSON reporter, groups results by feature (F1–F6) and by test
// type (unit / component / integration), and writes a committed markdown report.
// Report-on-red: a failing suite still produces the doc; the script then exits
// non-zero so CI can gate on it. Integration (.int.test.ts) tests need the dev
// Postgres (DATABASE_URL / billd_dev) up, same as `npm test`.

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';

const root = process.cwd();
const OUT = join(root, 'docs', 'test-report.md');

// Vitest does not auto-load .env. Integration (.int.test.ts) suites need
// DATABASE_URL, so load it here (without clobbering anything already exported)
// to keep the report a single self-contained command.
function loadDotenv(file) {
  if (!existsSync(file)) return;
  for (const raw of readFileSync(file, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    if (process.env[key] !== undefined) continue;
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    process.env[key] = val;
  }
}
loadDotenv(join(root, '.env'));
if (!process.env.DATABASE_URL) {
  console.warn('⚠ DATABASE_URL not set — integration (.int.test.ts) suites will not connect.');
}

// Feature buckets — first matching pattern wins; order matters.
const FEATURES = [
  ['F1 · Accounts', [/\(auth\)/, /\/login\//, /validation\/auth/]],
  ['F2 · Expenses', [/\/expenses\//, /expense/i, /amountMask/, /\/money\./, /pagination/, /validation\/expense/]],
  ['F3 · Categories', [/categor/i, /recentCategory/, /validation\/category/]],
  ['F4 · Budgets', [/budget/i, /validation\/budget/]],
  ['F5 · Dashboard', [/dashboard/i, /SpendChart/, /spendSeries/, /[Pp]rojection/, /\/page\.test/]],
  ['F6 · Recurring', [/recurr/i, /recurrence/, /validation\/recurring/]],
  ['Foundation', [/tokens\//, /colors\.test/]],
];

function featureOf(file) {
  for (const [name, pats] of FEATURES) {
    if (pats.some((p) => p.test(file))) return name;
  }
  return 'Unmapped';
}

function typeOf(file) {
  if (/\.int\.test\.[tj]sx?$/.test(file)) return 'integration';
  if (/\.tsx$/.test(file)) return 'component';
  return 'unit';
}

// --- run vitest, capture JSON ------------------------------------------------
const jsonPath = join(mkdtempSync(join(tmpdir(), 'billd-report-')), 'vitest.json');
console.log('▶ running vitest (json reporter)…');
const run = spawnSync(
  'npx',
  ['vitest', 'run', '--reporter=json', `--outputFile=${jsonPath}`],
  { cwd: root, encoding: 'utf8', stdio: ['ignore', 'inherit', 'inherit'] },
);

let report;
try {
  report = JSON.parse(readFileSync(jsonPath, 'utf8'));
} catch {
  console.error('✖ could not read vitest JSON output — aborting report.');
  process.exit(run.status ?? 1);
}

// --- normalise ---------------------------------------------------------------
const files = (report.testResults ?? []).map((suite) => {
  const file = relative(root, suite.name);
  const assertions = suite.assertionResults ?? [];
  const passed = assertions.filter((a) => a.status === 'passed').length;
  const failed = assertions.filter((a) => a.status === 'failed').length;
  const skipped = assertions.filter((a) => ['skipped', 'pending', 'todo'].includes(a.status)).length;
  const duration = (suite.endTime ?? 0) - (suite.startTime ?? 0);
  return {
    file,
    feature: featureOf(file),
    type: typeOf(file),
    total: assertions.length,
    passed,
    failed,
    skipped,
    duration,
    suiteStatus: suite.status,
    failures: assertions.filter((a) => a.status === 'failed').map((a) => a.fullName || a.title),
  };
});

const sum = (arr, k) => arr.reduce((n, x) => n + x[k], 0);
const totals = {
  files: files.length,
  tests: sum(files, 'total'),
  passed: sum(files, 'passed'),
  failed: sum(files, 'failed'),
  skipped: sum(files, 'skipped'),
};
const allGreen = totals.failed === 0;
const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

// --- render markdown ---------------------------------------------------------
const L = [];
L.push('# billd — Test Report');
L.push('');
L.push('> Generated by `npm run test:report` (`scripts/test-report.mjs`). Do not edit by hand.');
L.push(`> Generated: ${generatedAt}`);
L.push('');
L.push(`**${allGreen ? '✅ All green' : '❌ Failures present'}** — ` +
  `${totals.tests} tests across ${totals.files} files · ` +
  `${totals.passed} passed · ${totals.failed} failed · ${totals.skipped} skipped`);
L.push('');
L.push('_e2e (`e2e/smoke.spec.ts`, Playwright) runs separately via `npm run test:e2e` and is not included here._');
L.push('');

// by feature
L.push('## By feature');
L.push('');
L.push('| Feature | Files | Tests | Passed | Failed | Skipped | Status |');
L.push('|---------|------:|------:|-------:|-------:|--------:|:------:|');
const featureOrder = [...FEATURES.map((f) => f[0]), 'Unmapped'];
for (const name of featureOrder) {
  const fs = files.filter((f) => f.feature === name);
  if (!fs.length) continue;
  const f = (k) => sum(fs, k);
  const ok = f('failed') === 0;
  L.push(`| ${name} | ${fs.length} | ${f('total')} | ${f('passed')} | ${f('failed')} | ${f('skipped')} | ${ok ? '✅' : '❌'} |`);
}
L.push(`| **Total** | **${totals.files}** | **${totals.tests}** | **${totals.passed}** | **${totals.failed}** | **${totals.skipped}** | ${allGreen ? '✅' : '❌'} |`);
L.push('');

// by type
L.push('## By test type');
L.push('');
L.push('| Type | Files | Tests |');
L.push('|------|------:|------:|');
for (const t of ['unit', 'component', 'integration']) {
  const fs = files.filter((f) => f.type === t);
  if (!fs.length) continue;
  L.push(`| ${t} | ${fs.length} | ${sum(fs, 'total')} |`);
}
L.push('');

// per-file detail
L.push('## Per-file detail');
L.push('');
L.push('<details><summary>All test files</summary>');
L.push('');
L.push('| File | Feature | Type | Tests | Pass | Fail | ms |');
L.push('|------|---------|------|------:|-----:|-----:|---:|');
for (const f of [...files].sort((a, b) => a.feature.localeCompare(b.feature) || a.file.localeCompare(b.file))) {
  L.push(`| \`${f.file}\` | ${f.feature} | ${f.type} | ${f.total} | ${f.passed} | ${f.failed} | ${Math.round(f.duration)} |`);
}
L.push('');
L.push('</details>');
L.push('');

// failures
const failing = files.filter((f) => f.failed > 0);
if (failing.length) {
  L.push('## ❌ Failures');
  L.push('');
  for (const f of failing) {
    L.push(`- \`${f.file}\``);
    for (const name of f.failures) L.push(`  - ${name}`);
  }
  L.push('');
}

writeFileSync(OUT, L.join('\n') + '\n');
console.log(`\n✔ wrote ${relative(root, OUT)} — ${totals.tests} tests, ${totals.failed} failed`);
process.exit(allGreen ? 0 : 1);
